export default {
  products: [
    {
      id: 1,
      category: 'tv',
      model: 'KDL-XF9005',
      price: '500$',
      description: '55 inches tv',
      available: 7,
    },
    {
      id: 2,
      category: 'tv',
      model: 'KDL-XF9005',
      price: '500$',
      description: '65 inches tv',
      available: 2,
    },
    {
      id: 3,
      category: 'tv',
      model: 'KDL-XF9005',
      price: '500$',
      description: '55 inches tv',
      available: 1,
    },
    {
      id: 4,
      category: 'tv',
      model: 'KDL-XF9005',
      price: '500$',
      description: '85 inches tv',
      available: 3,
    },
    {
      id: 5,
      category: 'tv',
      model: 'KDL-XF9505',
      price: '700$',
      description: '55 inches tv',
      available: 0,
    },
    {
      id: 6,
      category: 'smartphone',
      model: 'KDL-XF9505',
      price: '700$',
      description: '55 inches tv',
      available: 5,
    },
    {
      id: 7,
      category: 'smartphone',
      model: 'KDL-XF9505',
      price: '700$',
      description: '55 inches tv',
      available: 2,
    },
    {
      id: 8,
      category: 'smartphone',
      model: 'KDL-XF9505',
      price: '700$',
      description: '55 inches tv',
      available: 0,
    },
    {
      id: 9,
      category: 'smartphone',
      model: 'KDL-XF9505',
      price: '700$',
      description: '55 inches tv',
      available: 3,
    },
    {
      id: 10,
      category: 'smartphone',
      model: 'KDL-XF9505',
      price: '700$',
      description: '55 inches tv',
      available: 2,
    },
  ],
};
